server:
  port: 8481

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  thymeleaf:
    cache: false

---
spring:
  profiles: p1

server:
  port: 8481

---
spring:
  profiles: p2

server:
  port: 8482

---
spring:
  profiles: p3

server:
  port: 8483
